version = 1
SPDX-PackageName = "Gardener machine-controller-manager-provider-sampleprovider"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/machine-controller-manager-provider-sampleprovider"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "cmd/machine-controller/main.go"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 The Kubernetes Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/google/go-cmp/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/go-cmp contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/beorn7/perks/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/beorn7/perks contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/modern-go/reflect2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/modern-go/reflect2 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/time/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/time contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/prometheus/client_golang/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/client_golang contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/component-base/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/component-base contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/prometheus/client_model/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/client_model contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/crypto/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/crypto contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/golang.org/x/net/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/net contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/client-go/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/client-go contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/apimachinery/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/apimachinery contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/hashicorp/golang-lru/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/hashicorp/golang-lru contributors."
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "vendor/github.com/prometheus/common/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/common contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/google.golang.org/appengine/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 google.golang.org/appengine contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/json-iterator/go/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/json-iterator/go contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/gopkg.in/yaml.v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/yaml.v2 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/onsi/gomega/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/gomega contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/k8s.io/api/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/api contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/imdario/mergo/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/imdario/mergo contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-isatty/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/ginkgo/reporters/stenographer/support/go-isatty contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/golang.org/x/text/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/text contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/matttproud/golang_protobuf_extensions/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/matttproud/golang_protobuf_extensions contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/oauth2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/oauth2 contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/utils/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/utils contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/hpcloud/tail/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/hpcloud/tail contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/gardener/machine-controller-manager/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/gardener/machine-controller-manager contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/davecgh/go-spew/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/davecgh/go-spew contributors."
SPDX-License-Identifier = "ISC"

[[annotations]]
path = "vendor/k8s.io/cluster-bootstrap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/cluster-bootstrap contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/onsi/ginkgo/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/ginkgo contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/golang/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/golang/groupcache/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang/groupcache contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/gogo/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/gogo/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/gopkg.in/tomb.v1/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/tomb.v1 contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/spf13/pflag/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/spf13/pflag contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/klog/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/klog contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/prometheus/procfs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/procfs contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/kube-openapi/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/kube-openapi contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/evanphx/json-patch/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/evanphx/json-patch contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/modern-go/concurrent/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/modern-go/concurrent contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/googleapis/gnostic/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/googleapis/gnostic contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/google/gofuzz/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/gofuzz contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/sys/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/sys contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/apiserver/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/apiserver contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/gopkg.in/fsnotify.v1/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/fsnotify.v1 contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/gopkg.in/inf.v0/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/inf.v0 contributors."
SPDX-License-Identifier = "BSD-3-Clause"
